import SwiftData
import Foundation

enum SeedData {
    static func seedIfNeeded(context: ModelContext) {
        let descriptor = FetchDescriptor<Exercise>()
        let count = (try? context.fetchCount(descriptor)) ?? 0
        guard count == 0 else { return }

        for ex in allExercises {
            context.insert(ex)
        }
        try? context.save()
    }

    static var allExercises: [Exercise] {
        chestExercises + backExercises + shoulderExercises + armExercises +
        legExercises + coreExercises + cardioExercises + fullBodyExercises
    }

    // MARK: - Chest
    static var chestExercises: [Exercise] {[
        Exercise(name: "Barbell Bench Press", category: "Chest",
            primaryMuscles: ["Pectorals"], secondaryMuscles: ["Triceps", "Front Delts"],
            equipment: "Barbell",
            instructions: "Lie on bench, grip bar slightly wider than shoulder-width. Lower bar to mid-chest, press back up to full extension."),
        Exercise(name: "Incline Barbell Bench Press", category: "Chest",
            primaryMuscles: ["Upper Pectorals"], secondaryMuscles: ["Triceps", "Front Delts"],
            equipment: "Barbell",
            instructions: "Set bench to 30–45°. Lower bar to upper chest, press up and slightly back."),
        Exercise(name: "Decline Barbell Bench Press", category: "Chest",
            primaryMuscles: ["Lower Pectorals"], secondaryMuscles: ["Triceps"],
            equipment: "Barbell",
            instructions: "Set bench to -15–30°. Lower bar to lower chest, press back up."),
        Exercise(name: "Dumbbell Bench Press", category: "Chest",
            primaryMuscles: ["Pectorals"], secondaryMuscles: ["Triceps", "Front Delts"],
            equipment: "Dumbbell",
            instructions: "Hold dumbbells at chest level, press up until arms are nearly straight, lower with control."),
        Exercise(name: "Incline Dumbbell Press", category: "Chest",
            primaryMuscles: ["Upper Pectorals"], secondaryMuscles: ["Triceps"],
            equipment: "Dumbbell",
            instructions: "Set bench to 30–45°. Press dumbbells up from chest level."),
        Exercise(name: "Dumbbell Fly", category: "Chest",
            primaryMuscles: ["Pectorals"], secondaryMuscles: ["Biceps"],
            equipment: "Dumbbell",
            instructions: "Lie flat, arms slightly bent. Open arms wide, lower until stretch, bring back together above chest."),
        Exercise(name: "Incline Dumbbell Fly", category: "Chest",
            primaryMuscles: ["Upper Pectorals"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Same as dumbbell fly but on incline bench."),
        Exercise(name: "Cable Fly", category: "Chest",
            primaryMuscles: ["Pectorals"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Stand between cables set at shoulder height. With arms slightly bent, bring hands together in front of chest."),
        Exercise(name: "Push-up", category: "Chest",
            primaryMuscles: ["Pectorals"], secondaryMuscles: ["Triceps", "Core"],
            equipment: "Bodyweight",
            instructions: "Start in high plank. Lower chest to floor keeping elbows at ~45°, push back up."),
        Exercise(name: "Weighted Dips", category: "Chest",
            primaryMuscles: ["Lower Pectorals"], secondaryMuscles: ["Triceps"],
            equipment: "Bodyweight",
            instructions: "Lean forward slightly on dip bars. Lower until upper arms are parallel to floor, press back up."),
        Exercise(name: "Pec Deck Machine", category: "Chest",
            primaryMuscles: ["Pectorals"], secondaryMuscles: [],
            equipment: "Machine",
            instructions: "Sit at machine, grip handles, bring arms together squeezing chest."),
        Exercise(name: "Landmine Press", category: "Chest",
            primaryMuscles: ["Upper Pectorals"], secondaryMuscles: ["Shoulders"],
            equipment: "Barbell",
            instructions: "Hold end of barbell with one hand, press upward and forward."),
    ]}

    // MARK: - Back
    static var backExercises: [Exercise] {[
        Exercise(name: "Conventional Deadlift", category: "Back",
            primaryMuscles: ["Erectors", "Glutes", "Hamstrings"], secondaryMuscles: ["Traps", "Lats", "Core"],
            equipment: "Barbell",
            instructions: "Stand with bar over mid-foot. Hinge at hips, grip bar, drive through floor keeping back flat."),
        Exercise(name: "Romanian Deadlift", category: "Back",
            primaryMuscles: ["Hamstrings", "Glutes"], secondaryMuscles: ["Erectors", "Lats"],
            equipment: "Barbell",
            instructions: "Start standing with bar at hip. Hinge forward, push hips back, lower bar along legs, return to standing."),
        Exercise(name: "Pull-up", category: "Back",
            primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps", "Rear Delts"],
            equipment: "Bodyweight",
            instructions: "Hang from bar with overhand grip. Pull chest to bar, lower with control."),
        Exercise(name: "Chin-up", category: "Back",
            primaryMuscles: ["Lats", "Biceps"], secondaryMuscles: ["Rear Delts"],
            equipment: "Bodyweight",
            instructions: "Hang from bar with underhand grip. Pull chin over bar."),
        Exercise(name: "Weighted Pull-up", category: "Back",
            primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps"],
            equipment: "Bodyweight",
            instructions: "Same as pull-up with added weight via belt or vest."),
        Exercise(name: "Barbell Row", category: "Back",
            primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps", "Rear Delts"],
            equipment: "Barbell",
            instructions: "Hinge to ~45°, row bar to lower chest/upper abs, squeeze shoulder blades."),
        Exercise(name: "Pendlay Row", category: "Back",
            primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps"],
            equipment: "Barbell",
            instructions: "Bar starts on floor each rep. Explosively row to lower chest, lower to floor."),
        Exercise(name: "Dumbbell Row", category: "Back",
            primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps"],
            equipment: "Dumbbell",
            instructions: "One knee on bench. Row dumbbell to hip, elbow high."),
        Exercise(name: "T-Bar Row", category: "Back",
            primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps"],
            equipment: "Barbell",
            instructions: "Straddle bar anchored at one end. Row the free end to chest."),
        Exercise(name: "Seated Cable Row", category: "Back",
            primaryMuscles: ["Rhomboids", "Lats"], secondaryMuscles: ["Biceps"],
            equipment: "Cable",
            instructions: "Sit upright, pull handle to lower abs, squeeze shoulder blades, return with control."),
        Exercise(name: "Lat Pulldown", category: "Back",
            primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps", "Rear Delts"],
            equipment: "Cable",
            instructions: "Grip bar wider than shoulders. Pull to upper chest, squeeze lats."),
        Exercise(name: "Close-Grip Lat Pulldown", category: "Back",
            primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps"],
            equipment: "Cable",
            instructions: "Use close neutral-grip attachment. Pull to chest."),
        Exercise(name: "Straight Arm Pulldown", category: "Back",
            primaryMuscles: ["Lats"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Stand, arms extended forward. With slight elbow bend, drive hands to hips."),
        Exercise(name: "Face Pull", category: "Back",
            primaryMuscles: ["Rear Delts", "Rhomboids"], secondaryMuscles: ["External Rotators"],
            equipment: "Cable",
            instructions: "Set cable at forehead height. Pull handles to face, flare elbows high."),
        Exercise(name: "Rack Pull", category: "Back",
            primaryMuscles: ["Erectors", "Traps"], secondaryMuscles: ["Glutes"],
            equipment: "Barbell",
            instructions: "Deadlift from knee height. Primarily targets upper back."),
        Exercise(name: "Hyperextension", category: "Back",
            primaryMuscles: ["Erectors"], secondaryMuscles: ["Glutes", "Hamstrings"],
            equipment: "Machine",
            instructions: "Secure feet on hyperextension bench. Lower torso, then raise back to neutral."),
        Exercise(name: "Good Morning", category: "Back",
            primaryMuscles: ["Erectors", "Hamstrings"], secondaryMuscles: ["Glutes"],
            equipment: "Barbell",
            instructions: "Bar on shoulders, hinge forward with slight knee bend, return to standing."),
    ]}

    // MARK: - Shoulders
    static var shoulderExercises: [Exercise] {[
        Exercise(name: "Barbell Overhead Press", category: "Shoulders",
            primaryMuscles: ["Front Delts", "Side Delts"], secondaryMuscles: ["Triceps", "Upper Pectorals"],
            equipment: "Barbell",
            instructions: "Stand with bar at upper chest. Press overhead to full lockout, lower with control."),
        Exercise(name: "Seated Dumbbell Press", category: "Shoulders",
            primaryMuscles: ["Front Delts", "Side Delts"], secondaryMuscles: ["Triceps"],
            equipment: "Dumbbell",
            instructions: "Sit upright, press dumbbells from shoulder level overhead."),
        Exercise(name: "Arnold Press", category: "Shoulders",
            primaryMuscles: ["All Delts"], secondaryMuscles: ["Triceps"],
            equipment: "Dumbbell",
            instructions: "Start with dumbbells in front of face, rotate palms outward as you press overhead."),
        Exercise(name: "Lateral Raise", category: "Shoulders",
            primaryMuscles: ["Side Delts"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Stand with dumbbells at sides. Raise arms to shoulder height, lower with control."),
        Exercise(name: "Cable Lateral Raise", category: "Shoulders",
            primaryMuscles: ["Side Delts"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Cable at hip level, arm across body. Raise to shoulder height."),
        Exercise(name: "Front Raise", category: "Shoulders",
            primaryMuscles: ["Front Delts"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Stand with dumbbells in front of thighs. Raise to shoulder height, alternating or together."),
        Exercise(name: "Rear Delt Fly", category: "Shoulders",
            primaryMuscles: ["Rear Delts"], secondaryMuscles: ["Rhomboids"],
            equipment: "Dumbbell",
            instructions: "Bend forward ~90°. Raise dumbbells out to sides, squeeze rear delts."),
        Exercise(name: "Cable Rear Delt Fly", category: "Shoulders",
            primaryMuscles: ["Rear Delts"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Cross cables at face height, pull to sides in reverse fly motion."),
        Exercise(name: "Barbell Shrug", category: "Shoulders",
            primaryMuscles: ["Traps"], secondaryMuscles: [],
            equipment: "Barbell",
            instructions: "Hold bar in front. Elevate shoulders straight up, hold 1 second, lower."),
        Exercise(name: "Dumbbell Shrug", category: "Shoulders",
            primaryMuscles: ["Traps"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Hold dumbbells at sides. Elevate shoulders straight up."),
        Exercise(name: "Upright Row", category: "Shoulders",
            primaryMuscles: ["Side Delts", "Traps"], secondaryMuscles: ["Biceps"],
            equipment: "Barbell",
            instructions: "Hold bar with narrow grip. Pull to chin level, elbows flared."),
    ]}

    // MARK: - Arms
    static var armExercises: [Exercise] {[
        Exercise(name: "Barbell Curl", category: "Arms",
            primaryMuscles: ["Biceps"], secondaryMuscles: ["Brachialis"],
            equipment: "Barbell",
            instructions: "Stand with bar at hip. Curl to shoulder height, lower with control."),
        Exercise(name: "EZ-Bar Curl", category: "Arms",
            primaryMuscles: ["Biceps"], secondaryMuscles: ["Brachialis"],
            equipment: "Barbell",
            instructions: "Same as barbell curl with EZ-bar to reduce wrist stress."),
        Exercise(name: "Dumbbell Curl", category: "Arms",
            primaryMuscles: ["Biceps"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Stand or sit. Curl dumbbell(s) to shoulder, supinate wrist at top."),
        Exercise(name: "Hammer Curl", category: "Arms",
            primaryMuscles: ["Brachialis", "Biceps"], secondaryMuscles: ["Brachioradialis"],
            equipment: "Dumbbell",
            instructions: "Neutral grip (thumbs up). Curl without rotating wrist."),
        Exercise(name: "Incline Dumbbell Curl", category: "Arms",
            primaryMuscles: ["Biceps Long Head"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Lie on incline bench. Let arms hang fully extended, curl to shoulder."),
        Exercise(name: "Preacher Curl", category: "Arms",
            primaryMuscles: ["Biceps Short Head"], secondaryMuscles: [],
            equipment: "Barbell",
            instructions: "Rest upper arms on preacher pad. Curl bar to chin level, lower fully."),
        Exercise(name: "Concentration Curl", category: "Arms",
            primaryMuscles: ["Biceps"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Sit, brace elbow on inner thigh. Curl with full supination at top."),
        Exercise(name: "Cable Curl", category: "Arms",
            primaryMuscles: ["Biceps"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Stand at cable with low pulley. Curl rope or bar attachment to chin."),
        Exercise(name: "Zottman Curl", category: "Arms",
            primaryMuscles: ["Biceps", "Brachioradialis"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Curl with underhand grip, rotate to overhand at top, lower with overhand."),
        Exercise(name: "Close-Grip Bench Press", category: "Arms",
            primaryMuscles: ["Triceps"], secondaryMuscles: ["Pectorals"],
            equipment: "Barbell",
            instructions: "Same as bench press with shoulder-width grip. Elbows stay tucked."),
        Exercise(name: "Tricep Pushdown", category: "Arms",
            primaryMuscles: ["Triceps"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Stand at high cable. With upper arms fixed, push handle down to full extension."),
        Exercise(name: "Overhead Tricep Extension", category: "Arms",
            primaryMuscles: ["Triceps Long Head"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Hold dumbbell overhead with both hands. Lower behind head, extend back up."),
        Exercise(name: "Skull Crusher", category: "Arms",
            primaryMuscles: ["Triceps"], secondaryMuscles: [],
            equipment: "Barbell",
            instructions: "Lie on bench. Bar above chest, lower to forehead by bending elbows, extend back up."),
        Exercise(name: "Tricep Kickback", category: "Arms",
            primaryMuscles: ["Triceps"], secondaryMuscles: [],
            equipment: "Dumbbell",
            instructions: "Hinge forward, upper arm parallel to floor. Extend forearm back."),
        Exercise(name: "Diamond Push-up", category: "Arms",
            primaryMuscles: ["Triceps"], secondaryMuscles: ["Pectorals"],
            equipment: "Bodyweight",
            instructions: "Place hands close together forming a diamond shape. Perform push-up."),
        Exercise(name: "Tricep Dips", category: "Arms",
            primaryMuscles: ["Triceps"], secondaryMuscles: ["Pectorals"],
            equipment: "Bodyweight",
            instructions: "Hands on bench behind you, feet on floor. Lower and raise using triceps."),
        Exercise(name: "Reverse Curl", category: "Arms",
            primaryMuscles: ["Brachioradialis"], secondaryMuscles: ["Biceps"],
            equipment: "Barbell",
            instructions: "Overhand grip. Curl bar to chin level."),
        Exercise(name: "Wrist Curl", category: "Arms",
            primaryMuscles: ["Forearm Flexors"], secondaryMuscles: [],
            equipment: "Barbell",
            instructions: "Forearms on bench. Curl wrists up, lower slowly."),
    ]}

    // MARK: - Legs
    static var legExercises: [Exercise] {[
        Exercise(name: "Barbell Back Squat", category: "Legs",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings", "Core"],
            equipment: "Barbell",
            instructions: "Bar across upper traps. Squat down until thighs parallel (or below), drive back up."),
        Exercise(name: "Front Squat", category: "Legs",
            primaryMuscles: ["Quads"], secondaryMuscles: ["Glutes", "Core"],
            equipment: "Barbell",
            instructions: "Bar in front rack position. Keep torso upright, squat below parallel."),
        Exercise(name: "Goblet Squat", category: "Legs",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Core"],
            equipment: "Dumbbell",
            instructions: "Hold dumbbell at chest. Squat deep, elbows track inside knees."),
        Exercise(name: "Leg Press", category: "Legs",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"],
            equipment: "Machine",
            instructions: "Place feet mid-platform. Lower until knees 90°, press to near lockout."),
        Exercise(name: "Romanian Deadlift (Legs)", category: "Legs",
            primaryMuscles: ["Hamstrings", "Glutes"], secondaryMuscles: ["Erectors"],
            equipment: "Barbell",
            instructions: "Hinge at hips, push hips back, lower bar to mid-shin, return."),
        Exercise(name: "Leg Curl (Lying)", category: "Legs",
            primaryMuscles: ["Hamstrings"], secondaryMuscles: [],
            equipment: "Machine",
            instructions: "Lie face down. Curl legs toward glutes, lower with control."),
        Exercise(name: "Leg Curl (Seated)", category: "Legs",
            primaryMuscles: ["Hamstrings"], secondaryMuscles: [],
            equipment: "Machine",
            instructions: "Sit at machine. Curl legs down and under seat."),
        Exercise(name: "Leg Extension", category: "Legs",
            primaryMuscles: ["Quads"], secondaryMuscles: [],
            equipment: "Machine",
            instructions: "Sit at machine. Extend legs to full lockout, lower with control."),
        Exercise(name: "Standing Calf Raise", category: "Legs",
            primaryMuscles: ["Gastrocnemius"], secondaryMuscles: ["Soleus"],
            equipment: "Machine",
            instructions: "On calf raise machine. Rise onto toes fully, lower below platform level."),
        Exercise(name: "Seated Calf Raise", category: "Legs",
            primaryMuscles: ["Soleus"], secondaryMuscles: ["Gastrocnemius"],
            equipment: "Machine",
            instructions: "Sit with knees at 90°. Rise onto toes, lower fully."),
        Exercise(name: "Bulgarian Split Squat", category: "Legs",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"],
            equipment: "Dumbbell",
            instructions: "Rear foot elevated on bench. Lunge down until rear knee nearly touches floor."),
        Exercise(name: "Lunge", category: "Legs",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"],
            equipment: "Dumbbell",
            instructions: "Step forward, lower back knee toward floor. Push back to start."),
        Exercise(name: "Walking Lunge", category: "Legs",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"],
            equipment: "Dumbbell",
            instructions: "Alternate forward lunges while walking across floor."),
        Exercise(name: "Hip Thrust", category: "Legs",
            primaryMuscles: ["Glutes"], secondaryMuscles: ["Hamstrings"],
            equipment: "Barbell",
            instructions: "Upper back on bench, bar across hips. Drive hips to ceiling, squeeze glutes at top."),
        Exercise(name: "Sumo Deadlift", category: "Legs",
            primaryMuscles: ["Glutes", "Hamstrings"], secondaryMuscles: ["Quads", "Adductors"],
            equipment: "Barbell",
            instructions: "Wide stance, toes angled out. Grip inside legs, deadlift to standing."),
        Exercise(name: "Hack Squat", category: "Legs",
            primaryMuscles: ["Quads"], secondaryMuscles: ["Glutes"],
            equipment: "Machine",
            instructions: "On hack squat machine. Lower until thighs parallel, drive up."),
        Exercise(name: "Glute Bridge", category: "Legs",
            primaryMuscles: ["Glutes"], secondaryMuscles: ["Hamstrings"],
            equipment: "Bodyweight",
            instructions: "Lie on back, feet flat. Drive hips up squeezing glutes, lower."),
        Exercise(name: "Sissy Squat", category: "Legs",
            primaryMuscles: ["Quads"], secondaryMuscles: [],
            equipment: "Bodyweight",
            instructions: "Hold support, lean back, bend knees while tilting torso back."),
    ]}

    // MARK: - Core
    static var coreExercises: [Exercise] {[
        Exercise(name: "Crunch", category: "Core",
            primaryMuscles: ["Rectus Abdominis"], secondaryMuscles: [],
            equipment: "Bodyweight",
            instructions: "Lie on back, hands behind head. Curl shoulders toward knees, lower."),
        Exercise(name: "Cable Crunch", category: "Core",
            primaryMuscles: ["Rectus Abdominis"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Kneel at cable with rope at head. Crunch downward pulling elbows to knees."),
        Exercise(name: "Plank", category: "Core",
            primaryMuscles: ["Core", "Transverse Abdominis"], secondaryMuscles: ["Shoulders"],
            equipment: "Bodyweight",
            instructions: "Forearms on floor, body in straight line. Hold position keeping core tight."),
        Exercise(name: "Side Plank", category: "Core",
            primaryMuscles: ["Obliques"], secondaryMuscles: ["Core"],
            equipment: "Bodyweight",
            instructions: "Side forearm on floor, body straight. Hold position."),
        Exercise(name: "Ab Rollout", category: "Core",
            primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"], secondaryMuscles: ["Lats"],
            equipment: "Other",
            instructions: "On knees with ab wheel. Roll out to full extension, pull back."),
        Exercise(name: "Russian Twist", category: "Core",
            primaryMuscles: ["Obliques"], secondaryMuscles: ["Rectus Abdominis"],
            equipment: "Bodyweight",
            instructions: "Sit with knees bent, lean back. Rotate torso side to side."),
        Exercise(name: "Hanging Leg Raise", category: "Core",
            primaryMuscles: ["Lower Abs", "Hip Flexors"], secondaryMuscles: [],
            equipment: "Bodyweight",
            instructions: "Hang from bar. Raise straight legs (or knees) to hip height."),
        Exercise(name: "Decline Sit-up", category: "Core",
            primaryMuscles: ["Rectus Abdominis"], secondaryMuscles: ["Hip Flexors"],
            equipment: "Bodyweight",
            instructions: "On decline bench, feet secured. Lower back fully, sit up to knees."),
        Exercise(name: "Dead Bug", category: "Core",
            primaryMuscles: ["Transverse Abdominis"], secondaryMuscles: ["Core"],
            equipment: "Bodyweight",
            instructions: "Lie on back, arms and legs up. Lower opposite arm and leg toward floor."),
        Exercise(name: "Bird Dog", category: "Core",
            primaryMuscles: ["Erectors", "Glutes"], secondaryMuscles: ["Core"],
            equipment: "Bodyweight",
            instructions: "On all fours. Extend opposite arm and leg, hold, return."),
        Exercise(name: "Pallof Press", category: "Core",
            primaryMuscles: ["Core", "Obliques"], secondaryMuscles: [],
            equipment: "Cable",
            instructions: "Stand side-on to cable. Press handle out from chest, hold, return. Anti-rotation."),
        Exercise(name: "Dragon Flag", category: "Core",
            primaryMuscles: ["Rectus Abdominis"], secondaryMuscles: ["Hip Flexors"],
            equipment: "Bodyweight",
            instructions: "Lie on bench gripping behind head. Raise legs and body straight up, lower as unit."),
        Exercise(name: "Hollow Body Hold", category: "Core",
            primaryMuscles: ["Transverse Abdominis", "Rectus Abdominis"], secondaryMuscles: [],
            equipment: "Bodyweight",
            instructions: "Lie on back, lower back pressed to floor. Extend arms and legs off floor."),
        Exercise(name: "L-Sit", category: "Core",
            primaryMuscles: ["Hip Flexors", "Rectus Abdominis"], secondaryMuscles: ["Triceps"],
            equipment: "Bodyweight",
            instructions: "Support body on parallel bars. Raise legs to 90°, hold."),
    ]}

    // MARK: - Cardio
    static var cardioExercises: [Exercise] {[
        Exercise(name: "Treadmill Run", category: "Cardio",
            primaryMuscles: ["Quads", "Hamstrings", "Calves"], secondaryMuscles: ["Glutes", "Core"],
            equipment: "Cardio Machine",
            instructions: "Set speed and incline. Maintain steady pace or use intervals."),
        Exercise(name: "Cycling", category: "Cardio",
            primaryMuscles: ["Quads", "Hamstrings"], secondaryMuscles: ["Glutes", "Calves"],
            equipment: "Cardio Machine",
            instructions: "Stationary bike. Adjust resistance and maintain target cadence."),
        Exercise(name: "Rowing Machine", category: "Cardio",
            primaryMuscles: ["Back", "Legs"], secondaryMuscles: ["Arms", "Core"],
            equipment: "Cardio Machine",
            instructions: "Drive with legs first, then lean back, then pull arms to lower chest."),
        Exercise(name: "Elliptical", category: "Cardio",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"],
            equipment: "Cardio Machine",
            instructions: "Low-impact full body movement. Maintain upright posture."),
        Exercise(name: "Jump Rope", category: "Cardio",
            primaryMuscles: ["Calves"], secondaryMuscles: ["Core", "Shoulders"],
            equipment: "Other",
            instructions: "Skip continuously or vary with double-unders and crossovers."),
        Exercise(name: "Stair Climber", category: "Cardio",
            primaryMuscles: ["Glutes", "Quads"], secondaryMuscles: ["Hamstrings", "Calves"],
            equipment: "Cardio Machine",
            instructions: "Climb at steady pace. Avoid leaning on handles excessively."),
        Exercise(name: "Assault Bike", category: "Cardio",
            primaryMuscles: ["Quads", "Shoulders"], secondaryMuscles: ["Core", "Arms"],
            equipment: "Cardio Machine",
            instructions: "Full body push-pull on pedals and handles simultaneously."),
        Exercise(name: "Swimming", category: "Cardio",
            primaryMuscles: ["Back", "Shoulders"], secondaryMuscles: ["Core", "Legs"],
            equipment: "Other",
            instructions: "Lap swimming. Vary strokes for different muscle emphasis."),
    ]}

    // MARK: - Full Body
    static var fullBodyExercises: [Exercise] {[
        Exercise(name: "Power Clean", category: "Full Body",
            primaryMuscles: ["Traps", "Glutes", "Quads"], secondaryMuscles: ["Hamstrings", "Core", "Shoulders"],
            equipment: "Barbell",
            instructions: "Explosive pull from floor, triple extension, catch bar in front rack position."),
        Exercise(name: "Clean and Jerk", category: "Full Body",
            primaryMuscles: ["Glutes", "Quads", "Shoulders"], secondaryMuscles: ["Traps", "Core"],
            equipment: "Barbell",
            instructions: "Clean bar to front rack. Dip and drive bar overhead, catch in split or squat."),
        Exercise(name: "Snatch", category: "Full Body",
            primaryMuscles: ["Glutes", "Traps", "Shoulders"], secondaryMuscles: ["Core", "Quads"],
            equipment: "Barbell",
            instructions: "Wide grip. Explosively pull bar from floor overhead in one motion."),
        Exercise(name: "Kettlebell Swing", category: "Full Body",
            primaryMuscles: ["Glutes", "Hamstrings"], secondaryMuscles: ["Core", "Shoulders"],
            equipment: "Kettlebell",
            instructions: "Hinge at hips, swing bell forward to shoulder height using hip extension."),
        Exercise(name: "Turkish Get-up", category: "Full Body",
            primaryMuscles: ["Shoulders", "Core"], secondaryMuscles: ["Glutes", "Hips"],
            equipment: "Kettlebell",
            instructions: "From lying with bell overhead, stand up and return through sequence of positions."),
        Exercise(name: "Burpee", category: "Full Body",
            primaryMuscles: ["Full Body"], secondaryMuscles: [],
            equipment: "Bodyweight",
            instructions: "From standing, squat to floor, jump feet back to push-up position, push up, jump feet in, jump up."),
        Exercise(name: "Box Jump", category: "Full Body",
            primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Calves", "Core"],
            equipment: "Other",
            instructions: "Stand before box. Dip and jump explosively onto box, land softly."),
        Exercise(name: "Thruster", category: "Full Body",
            primaryMuscles: ["Quads", "Shoulders"], secondaryMuscles: ["Triceps", "Glutes"],
            equipment: "Barbell",
            instructions: "Front squat combined with overhead press in one fluid movement."),
        Exercise(name: "Farmer's Walk", category: "Full Body",
            primaryMuscles: ["Traps", "Forearms"], secondaryMuscles: ["Core", "Quads"],
            equipment: "Dumbbell",
            instructions: "Hold heavy weights at sides, walk with upright posture for distance or time."),
        Exercise(name: "Battle Ropes", category: "Full Body",
            primaryMuscles: ["Shoulders", "Core"], secondaryMuscles: ["Arms", "Legs"],
            equipment: "Other",
            instructions: "Alternating or simultaneous wave motions with heavy ropes."),
    ]}
}
